title: Masters Basketball Tournaments

url: https://www.mastersbasketballtournaments.com
baseurl:

environment: production

#collections:
#  tournaments:
#    output: true

timezone: UTC

exclude:
  - Gemfile
  - Gemfile.lock
  - _assets

