title: Masters Basketball Tournaments

url: https://www.mastersbasketballtournaments.com
baseurl:

environment: production

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

timezone: UTC

exclude:
  - Gemfile
  - Gemfile.lock
  - _assets

